name: trivy 0.24.0
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: trivy txt
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'ubuntu:latest'
          format: 'table'
          output: trivy.txt
          exit-code: '0'

      - name: summary txt 
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### txt"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi

      - name: trivy json
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'ubuntu:latest'
          format: 'json'
          output: trivy.json
          exit-code: '0'

      - name: summary json
        run: |
          if [[ -s trivy.json ]]; then
            {
              echo "### json"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.json
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi

      - name: trivy sarif
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'ubuntu:latest'
          format: 'sarif'
          output: trivy.sarif
          exit-code: '0'
    
      - name: summary sarif
        run: |
          if [[ -s trivy.sarif ]]; then
            {
              echo "### sarif"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.sarif
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi

      - name: trivy github
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'ubuntu:latest'
          format: 'github'
          output: trivy.github
          exit-code: '0'
    
      - name: summary sarif
        run: |
          if [[ -s trivy.github ]]; then
            {
              echo "### github"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.github
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi
